layout: {
  ...existingLayout,
  pageMaxWidth: 1280,
  pagePanelPadding: 32,
  pagePanelPaddingMobile: 20,
  pageSectionGap: 24,
  sectionCardPadding: 24,
  sectionCardPaddingCompact: 20,
  settingsRowMinHeight: 72,
  subnavHeight: 52,
},
semantic: {
  ...existingSemantic,
  component: {
    ...existingSemantic.component,
    pageShell: {
      radius: 20,
      border: "1px solid",
      shadow: "none",
      background: "var(--color-surface)",
    },
    sectionCard: {
      radius: 16,
      border: "1px solid",
      shadow: "none",
      background: "var(--color-surface)",
    },
    subnavTab: {
      height: 52,
      radius: 0,
      indicatorHeight: 2,
    },
    selectionCard: {
      radius: 16,
      previewRadius: 12,
      borderWidth: 1,
      selectedBorderWidth: 2,
    },
  },
  typography: {
    ...existingSemantic.typography,
    pageTitle: {
      fontFamily: "var(--font-body)",
      fontSize: "1.875rem",
      fontWeight: 600,
      lineHeight: 1.2,
      letterSpacing: "-0.02em",
    },
    sectionTitle: {
      fontFamily: "var(--font-body)",
      fontSize: "1.125rem",
      fontWeight: 600,
      lineHeight: 1.4,
      letterSpacing: "-0.01em",
    },
    supportingText: {
      fontFamily: "var(--font-body)",
      fontSize: "0.875rem",
      fontWeight: 400,
      lineHeight: 1.6,
      letterSpacing: "0",
    },
    eyebrowLabel: {
      fontFamily: "var(--font-body)",
      fontSize: "0.875rem",
      fontWeight: 600,
      lineHeight: 1.4,
      letterSpacing: "0",
    },
  },
},
